import 'package:firebase_core/firebase_core.dart';

class NotificationInitOptions {
  const NotificationInitOptions({
    this.initializeFirebase = true,
    this.firebaseOptions,
    this.enableFcm = true,
    this.requestPermissionsAtStartup = true,
  });

  /// Whether this module should call `Firebase.initializeApp()` internally.
  ///
  /// Set this to `false` if your project initializes Firebase elsewhere.
  final bool initializeFirebase;

  /// Optional Firebase options generated by FlutterFire CLI.
  ///
  /// If your generated project has `firebase_options.dart`, pass
  /// `DefaultFirebaseOptions.currentPlatform` here when enabling FCM.
  final FirebaseOptions? firebaseOptions;

  /// Whether FCM (firebase_messaging) should be enabled.
  ///
  /// If disabled, the module will only provide local notifications.
  final bool enableFcm;

  /// Whether notification permissions should be requested during initialization.
  ///
  /// This uses `permission_handler`.
  final bool requestPermissionsAtStartup;
}
