# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    void_checks: ignore
  exclude:
    - "build/**"
    - "ios/**"
    - "android/**"
    - "windows/**"
    - "macos/**"
    - "linux/**"
    - "web/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - ".dart_tool/**"
    - "node_modules/**"
    - "assets/**"
    - "test/**"
    - "**/*.pbxproj"
    - "**/*.plist"
    - "**/*.xcconfig"
    - "**/*.xcworkspace"
    - "**/*.xcodeproj"
    - "**/*.gradle"
    - "**/*.properties"
    - "**/*.xml"
    - "**/*.kt"
    - "**/*.java"
    - "**/*.swift"
    - "**/*.h"
    - "**/*.cc"
    - "**/*.cpp"
    - "**/*.md"
    - "**/*.txt"
    - "**/*.pdf"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"
    - "**/*.lock"
    - "**/*.toml"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    unnecessary_this: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    use_key_in_widget_constructors: true

    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
